# Generated by Django 3.2.9 on 2021-12-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
