# Generated by Django 3.2.9 on 2021-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('year', models.IntegerField(default=None, max_length=4)),
                ('image', models.CharField(default=None, max_length=500)),
                ('colour', models.CharField(default=None, max_length=50)),
                ('steering', models.CharField(default=None, max_length=20)),
                ('passengers', models.IntegerField(default=None, max_length=2)),
                ('description', models.CharField(default=None, max_length=1500)),
                ('minprice', models.IntegerField(default=None, max_length=3)),
                ('hourly', models.IntegerField(default=None, max_length=4)),
            ],
        ),
    ]
