# Generated by Django 3.2.9 on 2021-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hourly',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='minprice',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
