# Generated by Django 3.2.9 on 2021-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_hourly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hourly',
            field=models.IntegerField(default=None),
        ),
    ]
