# Generated by Django 3.2.9 on 2021-12-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_hourly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=None, max_length=1500),
        ),
    ]
