# Generated by Django 3.2.9 on 2021-12-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='picture',
        ),
    ]
