# Generated by Django 3.2.9 on 2021-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('cars', '0006_rename_image_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.Service'),
        ),
    ]
